
insert into chess.PositionMap select 1,1,1
insert into chess.PositionMap select 2,1,2
insert into chess.PositionMap select 3,1,3
insert into chess.PositionMap select 4,1,4
insert into chess.PositionMap select 5,1,5
insert into chess.PositionMap select 6,1,6
insert into chess.PositionMap select 7,1,7
insert into chess.PositionMap select 8,1,8
insert into chess.PositionMap select 9,2,1
insert into chess.PositionMap select 10,2,2
insert into chess.PositionMap select 11,2,3
insert into chess.PositionMap select 12,2,4
insert into chess.PositionMap select 13,2,5
insert into chess.PositionMap select 14,2,6
insert into chess.PositionMap select 15,2,7
insert into chess.PositionMap select 16,2,8
insert into chess.PositionMap select 17,3,1
insert into chess.PositionMap select 18,3,2
insert into chess.PositionMap select 19,3,3
insert into chess.PositionMap select 20,3,4
insert into chess.PositionMap select 21,3,5
insert into chess.PositionMap select 22,3,6
insert into chess.PositionMap select 23,3,7
insert into chess.PositionMap select 24,3,8
insert into chess.PositionMap select 25,4,1
insert into chess.PositionMap select 26,4,2
insert into chess.PositionMap select 27,4,3
insert into chess.PositionMap select 28,4,4
insert into chess.PositionMap select 29,4,5
insert into chess.PositionMap select 30,4,6
insert into chess.PositionMap select 31,4,7
insert into chess.PositionMap select 32,4,8
insert into chess.PositionMap select 33,5,1
insert into chess.PositionMap select 34,5,2
insert into chess.PositionMap select 35,5,3
insert into chess.PositionMap select 36,5,4
insert into chess.PositionMap select 37,5,5
insert into chess.PositionMap select 38,5,6
insert into chess.PositionMap select 39,5,7
insert into chess.PositionMap select 40,5,8
insert into chess.PositionMap select 41,6,1
insert into chess.PositionMap select 42,6,2
insert into chess.PositionMap select 43,6,3
insert into chess.PositionMap select 44,6,4
insert into chess.PositionMap select 45,6,5
insert into chess.PositionMap select 46,6,6
insert into chess.PositionMap select 47,6,7
insert into chess.PositionMap select 48,6,8
insert into chess.PositionMap select 49,7,1
insert into chess.PositionMap select 50,7,2
insert into chess.PositionMap select 51,7,3
insert into chess.PositionMap select 52,7,4
insert into chess.PositionMap select 53,7,5
insert into chess.PositionMap select 54,7,6
insert into chess.PositionMap select 55,7,7
insert into chess.PositionMap select 56,7,8
insert into chess.PositionMap select 57,8,1
insert into chess.PositionMap select 58,8,2
insert into chess.PositionMap select 59,8,3
insert into chess.PositionMap select 60,8,4
insert into chess.PositionMap select 61,8,5
insert into chess.PositionMap select 62,8,6
insert into chess.PositionMap select 63,8,7
insert into chess.PositionMap select 64,8,8
